[CAMINHOS]
; atenção: use barras normais (/) ou duplas (\\) = 
pasta_do_sistema = D:\Max
pasta_das_versoes = D:\Max\Versões
caminho_do_ini = D:\Max\max.ini
caminho_do_7zip_exe = C:\Program Files (x86)\7-Zip\7z.exe

[EXECUTAVEIS]
nome_exe_cliente = MAX_manager2.exe
nome_exe_atualizador = MAX_Atualiza.exe

[CONFIG_INI_MAX]
ini_section = CON
ini_key = Initial catalog

[SQL_LAUDO]
sql_driver_lista = {ODBC Driver 17 for SQL Server}
sql_server_instance = localhost

[SQL_RESTORE]
servidor = localhost
usuario = sa
senha = macro01
odbc_driver_restore = {ODBC Driver 17 for SQL Server}

